export const FETCH_WEEKLY_FORECAST = 'FETCH_WEEKLY_FORECAST';
export const FETCH_WEEKLY_FORECAST_SUCCESS = 'FETCH_WEEKLY_FORECAST_SUCCESS';
export const FETCH_WEEKLY_FORECAST_ERROR = 'FETCH_WEEKLY_FORECAST_ERROR';